version: "3.8"

services:
  kpanel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kpanel
    restart: unless-stopped
    ports:
      - "2222:2222"
    volumes:
      - kpanel_data:/app/database
      - kpanel_logs:/app/logs
      - kpanel_conf:/app/conf
    environment:
      - NODE_ENV=production
      - PORT=2222
      - DATABASE_PATH=/app/database/kpanel.db
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-kpanel123}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-here-change-me}
      - SESSION_SECRET=${SESSION_SECRET:-your-session-secret-here-change-me}
      - FORCE_HTTP=true
      - DISABLE_HTTPS=true
      - NO_SSL=true
      - HTTP_ONLY=true
      - PUBLIC_IP=${PUBLIC_IP:-}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:2222 || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
    networks:
      - kpanel-network

volumes:
  kpanel_data:
    driver: local
  kpanel_conf:
    driver: local
  kpanel_logs:
    driver: local

networks:
  kpanel-network:
    driver: bridge
